services:

  bot:
    image: ghcr.io/vadimkholodilo/support-bot:latest
    build:
      context: .
    container_name: support-bot
    restart: always
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
    networks:
      - network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:alpine
    container_name: support-redis
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - network


networks:
  network:

volumes:
  redis-data:
