services:
  bot:
    profiles:
      - dev-bot
    pull_policy: build
    environment:
      REDIS_HOST: redis
      POSTGRES_DSN: postgresql+asyncpg://support_bot:support_bot@postgres:5432/support_bot

  migrate:
    pull_policy: build
    environment:
      REDIS_HOST: redis
      POSTGRES_DSN: postgresql+asyncpg://support_bot:support_bot@postgres:5432/support_bot

  postgres:
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    ports:
      - "127.0.0.1:6379:6379"